[package]
name = "sharkmer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"]}
rand = { version = "*"}
rayon = { version = "*"}
bloom = { version = "*"}
rustc-hash = { version = "*"}
dashmap = { version = "*"}

