package:
  name: sharkmer
  version: 1.0.0

source:
  url: https://github.com/caseywdunn/sharkmer/archive/refs/tags/v1.0.0.tar.gz
  sha256: 5afe6fb8b64c7ec910d94efd83c0c6c98dcf84a0a0dea1cf9f186b071742a23f

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('sharkmer', max_pin='x') }}

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - sharkmer --help

about:
  home: https://github.com/caseywdunn/sharkmer
  summary: "Kmer counter and seeded de Bruijn graph assembler for in silico PCR and genome size estimation"
  license: MIT
  license_file:
    - sharkmer/LICENSE
    - sharkmer/licenses/LICENSE.dependencies.json

extra:
  recipe-maintainers:
    - caseywdunn
