package:
  name: sharkmer_rust
  version: 0.1.0

source:
  path: .

requirements:
  build:
    - rust
  host:
    - rust

test:
  source_files:
    - Cargo.toml
    - src/**/*.rs  # or whichever files are needed to run the tests
  commands:
    - sharkmer --help
    - cargo test